
'use strict';
const VERSION='v0.26.06.10.2134';
const TERRAIN={plains:{name:'Plains',move:1,def:0,icon:'·'},forest:{name:'Forest',move:2,def:2,icon:'♣'},hills:{name:'Hills',move:2,def:1,icon:'⌂'},mountains:{name:'Mountains',move:3,def:3,icon:'▲'},water:{name:'Water',move:99,def:0,icon:'≈'},roads:{name:'Road',move:1,def:0,icon:'═'}};
const STRUCTS={town:{name:'Town',income:150,icon:'⌂'},city:{name:'City',income:300,icon:'⚙'},fortress:{name:'Fortress',income:200,icon:'▣'}};
const COLORS=['#b94a42','#4688c7','#4a9b62','#8c5eb8','#c77734','#4da5a8','#bd5d86','#8a8a8a'];
const COMMANDERS={
 'Steam Marshal':{name:'Marshal Verena Brasswake',icon:'🎖️',atk:3,def:1,heal:12,ai:'aggressive',desc:'Marshal Verena Brasswake — big-caped offensive commander. Aura: +3 Atk / +1 Def / +12 Heal. Favors disciplined advances and finishing blows.'},
 'Archmage':{name:'Archmage Aurelian Voxgear',icon:'🔮',atk:1,def:1,heal:20,ai:'arcane',desc:'Archmage Aurelian Voxgear — impossible hair, rune-engine mantle, and arcane artillery instincts. Aura: +1 Atk / +1 Def / +20 Heal.'},
 'Sky Admiral':{name:'Admiral Seraphine Cloudreaver',icon:'🪽',atk:2,def:0,heal:10,moveBias:1,ai:'mobile',desc:'Admiral Seraphine Cloudreaver — skyfleet duelist with a giant storm cape. Aura: +2 Atk / +0 Def / +10 Heal. Favors mobility and air power.'},
 'Iron Priest':{name:'Father Malrick Ironhalo',icon:'⚒️',atk:0,def:3,heal:16,ai:'defensive',desc:'Father Malrick Ironhalo — brass-haloed war priest in impossible shoulder armor. Aura: +0 Atk / +3 Def / +16 Heal. Favors fortresses and survival.'}
};
const UNITS={
 Infantry:{cost:300,hp:100,mv:3,atk:26,def:8,range:1,icon:'⚔️',class:'banner',capture:true,tags:['infantry'],squad:10},
 Pikemen:{cost:350,hp:100,mv:3,atk:24,def:10,range:1,icon:'𐂂',class:'banner',capture:true,tags:['pike'],squad:10},
 Cavalry:{cost:650,hp:100,mv:5,atk:34,def:12,range:1,icon:'♞',class:'banner',capture:false,tags:['cavalry'],squad:5},
 Riflemen:{cost:500,hp:100,mv:3,atk:25,def:7,range:2,icon:'⌐',class:'steam',capture:true,tags:['rifle'],squad:10},
 Artillery:{cost:900,hp:100,mv:2,atk:44,def:5,range:3,icon:'☄',class:'steam',capture:false,tags:['artillery'],squad:5},
 'Steam Tank':{cost:1100,hp:120,mv:3,atk:40,def:20,range:1,icon:'▰',class:'steam',capture:false,tags:['tank']},
 Airship:{cost:1200,hp:100,mv:5,atk:36,def:11,range:2,icon:'☁',class:'air',capture:false,tags:['air'],squad:5},
 Gyrocopter:{cost:750,hp:80,mv:6,atk:28,def:8,range:1,icon:'✣',class:'gyro air',capture:false,tags:['air','gyro'],squad:5},
 Mage:{cost:800,hp:75,mv:3,atk:38,def:5,range:2,icon:'✦',class:'magic',capture:true,tags:['mage'],squad:10},
 Assassin:{cost:700,hp:75,mv:4,atk:36,def:6,range:1,icon:'☾',class:'banner',capture:true,tags:['assassin'],squad:10},
 Commander:{cost:0,hp:160,mv:4,atk:42,def:18,range:1,icon:'♛',class:'banner',capture:false,tags:['commander'],squad:1}
};
const COUNTERS={
 pike:{cavalry:1.65}, cavalry:{artillery:1.55,rifle:1.25}, artillery:{tank:1.65,fortress:1.2}, rifle:{air:1.65,gyro:1.45}, assassin:{mage:1.9,commander:1.2}, tank:{infantry:1.65,pike:1.2}, mage:{tank:1.25,infantry:1.2}, air:{artillery:1.3}, gyro:{assassin:1.25}
};

const AI_LEVELS={
 Recruit:{rank:1,think:'loose',bonusGold:0,aggression:.65,caution:.25},
 Soldier:{rank:2,think:'basic',bonusGold:40,aggression:.85,caution:.45},
 Captain:{rank:3,think:'solid',bonusGold:80,aggression:1.05,caution:.65},
 Warlord:{rank:4,think:'sharp',bonusGold:120,aggression:1.25,caution:.85},
 'Iron Tyrant':{rank:5,think:'ruthless',bonusGold:180,aggression:1.45,caution:1.1}
};
const DEFAULT_SLOT_KINDS=['Human','AI','AI','AI','Closed','Closed','Closed','Closed'];
const DEFAULT_AI_LEVELS=['Captain','Soldier','Captain','Warlord','Soldier','Captain','Warlord','Iron Tyrant'];
const COMMANDER_ORDER=Object.keys(COMMANDERS);
let state=null, selected=null, highlights=[], rng=Math.random, lastTile=null, lastTurnSummary=null;
function $(id){return document.getElementById(id)}
function log(msg){ if(!state) return; state.log.unshift(`[Turn ${state.turn}] ${msg}`); state.log=state.log.slice(0,90); renderLog(); }
function seeded(seed){let h=2166136261>>>0; for(let i=0;i<seed.length;i++){h^=seed.charCodeAt(i);h=Math.imul(h,16777619)} return function(){h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296}}

const audio={ctx:null,musicOn:true,sfxOn:true,musicVol:.35,sfxVol:.7,loop:null,theme:'title',step:0,next:0,fileEl:null};
const TRACKS={title:'assets/audio/music/title_theme.mp3',turn:'assets/audio/music/player_turn_theme.mp3',battle:'assets/audio/music/battle_theme.mp3',tension:'assets/audio/music/tension_theme.mp3',observer:'assets/audio/music/observer_council_theme.mp3',victory:'assets/audio/music/victory_fanfare.mp3',defeat:'assets/audio/music/defeat_sting.mp3', danger:'assets/audio/music/commander_danger_theme.mp3', final:'assets/audio/music/final_kingdom_theme.mp3'};
function loadAudioSettings(){try{let s=JSON.parse(localStorage.getItem('ik_audio')||'{}'); if(typeof s.musicOn==='boolean')audio.musicOn=s.musicOn; if(typeof s.sfxOn==='boolean')audio.sfxOn=s.sfxOn; if(typeof s.musicVol==='number')audio.musicVol=s.musicVol; if(typeof s.sfxVol==='number')audio.sfxVol=s.sfxVol; if(s.animSpeed&&$('animSpeed'))$('animSpeed').value=s.animSpeed; if(s.battleView&&$('battleView'))$('battleView').value=s.battleView;}catch(e){} updateAudioUI();}
function saveAudioSettings(){audio.musicVol=(+$('musicVol')?.value||35)/100; audio.sfxVol=(+$('sfxVol')?.value||70)/100; if(audio.fileEl)audio.fileEl.volume=audio.musicVol; localStorage.setItem('ik_audio',JSON.stringify({musicOn:audio.musicOn,sfxOn:audio.sfxOn,musicVol:audio.musicVol,sfxVol:audio.sfxVol,animSpeed:$('animSpeed')?.value||'Normal',battleView:$('battleView')?.value||'On'})); updateAudioUI();}
function updateAudioUI(){if($('musicVol'))$('musicVol').value=Math.round(audio.musicVol*100); if($('sfxVol'))$('sfxVol').value=Math.round(audio.sfxVol*100); if($('musicToggle')){$('musicToggle').textContent=audio.musicOn?'Music On':'Music Off';$('musicToggle').classList.toggle('active',audio.musicOn)} if($('sfxToggle')){$('sfxToggle').textContent=audio.sfxOn?'SFX On':'SFX Off';$('sfxToggle').classList.toggle('active',audio.sfxOn)} if($('audioBtn'))$('audioBtn').textContent=audio.ctx?'Audio Enabled':'Enable Audio';}
function enableAudio(){if(!audio.ctx){audio.ctx=new (window.AudioContext||window.webkitAudioContext)(); audio.next=audio.ctx.currentTime+.05; startMusic('title');} if(audio.ctx.state==='suspended')audio.ctx.resume(); updateAudioUI(); return audio.ctx;}
function toggleMusic(){audio.musicOn=!audio.musicOn; saveAudioSettings(); if(audio.musicOn)enableAudio();}
function toggleSfx(){audio.sfxOn=!audio.sfxOn; saveAudioSettings();}
function startMusic(theme){audio.theme=theme; if(audio.loop){clearInterval(audio.loop);audio.loop=null;} if(audio.fileEl){audio.fileEl.pause();audio.fileEl=null;} if(!audio.ctx||!audio.musicOn)return; if(TRACKS[theme]){let el=new Audio(TRACKS[theme]); audio.fileEl=el; el.loop=!['victory','defeat'].includes(theme); el.volume=audio.musicVol; el.play().catch(()=>{audio.fileEl=null; audio.step=0; audio.next=audio.ctx.currentTime+.05; audio.loop=setInterval(scheduleMusic,90);}); return;} audio.step=0; audio.next=audio.ctx.currentTime+.05; audio.loop=setInterval(scheduleMusic,90);}
function noteFreq(n){return 440*Math.pow(2,(n-69)/12)}
function tone(freq,t,dur,type='square',vol=.2){if(!audio.ctx)return; let ctx=audio.ctx,o=ctx.createOscillator(),g=ctx.createGain(); o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol*audio.musicVol,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+dur+.02)}
function drum(t,kind='tick',vol=.25){if(!audio.ctx)return; let ctx=audio.ctx,osc=ctx.createOscillator(),g=ctx.createGain(); osc.type=kind==='kick'?'sine':'triangle'; osc.frequency.setValueAtTime(kind==='kick'?110:220,t); osc.frequency.exponentialRampToValueAtTime(kind==='kick'?45:90,t+.12); g.gain.setValueAtTime(vol*audio.musicVol,t); g.gain.exponentialRampToValueAtTime(.0001,t+.16); osc.connect(g).connect(ctx.destination); osc.start(t); osc.stop(t+.18)}
function scheduleMusic(){if(!audio.ctx||!audio.musicOn)return; const ctx=audio.ctx,tempo=.18; const patterns={title:[57,60,64,67,69,67,64,60],turn:[60,64,67,72,71,67,64,62],tension:[55,58,62,65,67,65,62,58],observer:[52,55,59,62,64,62,59,55]}; let pat=patterns[audio.theme]||patterns.turn; while(audio.next<ctx.currentTime+.45){let i=audio.step%16,root=pat[i%pat.length]; if(i%2===0)tone(noteFreq(root),audio.next,.14,'square',.12); if(i%4===0)tone(noteFreq(root-12),audio.next,.18,'sawtooth',.08); if(i%4===2)tone(noteFreq(root+7),audio.next,.12,'triangle',.07); if(i%4===0)drum(audio.next,'kick',.16); else if(i%2===0)drum(audio.next,'tick',.07); audio.next+=tempo; audio.step++;}}
function sfx(kind='click'){if(!audio.sfxOn)return; enableAudio(); if(!audio.ctx)return; let ctx=audio.ctx,t=ctx.currentTime+.01,vol=audio.sfxVol; function blip(f,d,type='square',v=.15){let o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v*vol,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+d+.02)} if(kind==='move')blip(330,.08,'triangle',.12); if(kind==='hit'){blip(95,.14,'sawtooth',.2); setTimeout(()=>blip(180,.07,'square',.1),40)} if(kind==='heavy'){blip(70,.22,'sawtooth',.25)} if(kind==='heal')blip(640,.18,'triangle',.12); if(kind==='turn')blip(523,.12,'square',.1); if(kind==='win'){if(audio.ctx&&TRACKS.victory){let el=new Audio(TRACKS.victory);el.volume=audio.sfxVol;el.play().catch(()=>{});} [523,659,784].forEach((f,i)=>setTimeout(()=>{blip(f,.18,'square',.15)},i*90))}}
function setThemeForCurrent(){if(!state)return; if(player().observer)startMusic('observer'); else startMusic(player().alive?'turn':'tension');}

function openNewGame(){
 let wrap=$('slotSetup'); if(wrap){wrap.innerHTML='<div class="head">Slot</div><div class="head">Type</div><div class="head">Difficulty</div><div class="head">Commander</div><div class="head">Name</div>'; for(let i=0;i<8;i++)wrap.innerHTML+=slotSetupRow(i); updateSlotRows();}
 $('ngSeed').value='';$('newGameModal').classList.add('show')}
function slotSetupRow(i){let kind=DEFAULT_SLOT_KINDS[i]||'Closed', lvl=DEFAULT_AI_LEVELS[i]||'Soldier', cmd=COMMANDER_ORDER[i%COMMANDER_ORDER.length], nm=i===0?'Player 1':`Kingdom ${i+1}`; return `<div class="slotRow" id="slotRow${i}"><div>${i+1}</div><select id="slotKind${i}" onchange="updateSlotRows()"><option ${kind==='Human'?'selected':''}>Human</option><option ${kind==='AI'?'selected':''}>AI</option><option ${kind==='Closed'?'selected':''}>Closed</option></select><select id="slotDiff${i}">${Object.keys(AI_LEVELS).map(x=>`<option ${x===lvl?'selected':''}>${x}</option>`).join('')}</select><select id="slotCmd${i}" onchange="updateCommanderPreview(${i})">${COMMANDER_ORDER.map(x=>`<option ${x===cmd?'selected':''}>${x}</option>`).join('')}</select><input id="slotName${i}" value="${nm}"></div>`;}
function updateSlotRows(){for(let i=0;i<8;i++){let kind=$(`slotKind${i}`)?.value||'Closed', row=$(`slotRow${i}`); if(row)row.classList.toggle('closedSlot',kind==='Closed'); if($(`slotDiff${i}`))$(`slotDiff${i}`).disabled=kind!=='AI'; if($(`slotCmd${i}`))$(`slotCmd${i}`).disabled=kind==='Closed'; if($(`slotName${i}`))$(`slotName${i}`).disabled=kind==='Closed';}}
function updateCommanderPreview(i){}
function readGameSetup(){let slots=[]; for(let i=0;i<8;i++){let kind=$(`slotKind${i}`)?.value||DEFAULT_SLOT_KINDS[i]||'Closed'; if(kind==='Closed')continue; let commanderClass=$(`slotCmd${i}`)?.value||COMMANDER_ORDER[i%COMMANDER_ORDER.length]; let aiDifficulty=$(`slotDiff${i}`)?.value||'Soldier'; let name=($(`slotName${i}`)?.value||`Kingdom ${i+1}`).trim()||`Kingdom ${i+1}`; slots.push({id:slots.length,slot:i,kind,aiDifficulty,commanderClass,name});} if(!slots.length)slots.push({id:0,slot:0,kind:'Human',aiDifficulty:'Captain',commanderClass:'Steam Marshal',name:'Player 1'}); if(!slots.some(s=>s.kind==='Human'))slots[0].kind='Human'; return slots;}
function closeModal(id){$(id).classList.remove('show')} function showHelp(){$('helpModal').classList.add('show')}
function startNewGame(){let configs=readGameSetup();let p=configs.length;let size=$('ngSize').value;let seed=$('ngSeed').value||String(Date.now()); rng=seeded(seed); const dims={Small:[12,10],Medium:[16,12],Large:[22,16]}[size];
 state={version:VERSION,seed,size,w:dims[0],h:dims[1],turn:1,current:0,nextUnitId:1,players:[],map:[],units:[],log:[],weather:'Clear',turnEvents:[],lastIncome:0,aiRunning:false};
 for(let y=0;y<state.h;y++){for(let x=0;x<state.w;x++){state.map.push({x,y,t:randomTerrain(x,y),s:null,owner:null})}}
 scatterStructures(p); createPlayers(configs); placeStarts(); startTurn(); closeModal('newGameModal'); log(`New ${size} war started. Seed: ${seed}. ${configs.filter(s=>s.kind==='AI').length} AI kingdoms joined.`); enableAudio(); setThemeForCurrent(); render(); maybeRunAI(); }
function randomTerrain(x,y){let r=rng(); if(r<.09)return 'water'; if(r<.22)return 'forest'; if(r<.34)return 'hills'; if(r<.42)return 'mountains'; if(r<.52)return 'roads'; return 'plains'}
function tile(x,y){return state.map[y*state.w+x]} function unitAt(x,y){return state.units.find(u=>u.x==x&&u.y==y&&u.hp>0)} function player(){return state.players[state.current]}
function dist(a,b){return Math.abs(a.x-b.x)+Math.abs(a.y-b.y)}
function scatterStructures(p){let spots=[]; for(let y=1;y<state.h-1;y++)for(let x=1;x<state.w-1;x++) if(tile(x,y).t!=='water'&&tile(x,y).t!=='mountains') spots.push({x,y});
 for(let i=0;i<Math.floor(state.w*state.h/18);i++){let s=spots.splice(Math.floor(rng()*spots.length),1)[0]; if(!s)break; let rr=rng(); tile(s.x,s.y).s=rr<.18?'fortress':rr<.55?'city':'town';}
}
function createPlayers(configs){state.players=[]; configs.forEach((cfg,i)=>{let cls=cfg.commanderClass||COMMANDER_ORDER[i%COMMANDER_ORDER.length], cmd=COMMANDERS[cls]; state.players.push({id:i,name:cfg.name||`Kingdom ${i+1}`,color:COLORS[i],gold:1000+(cfg.kind==='AI'?(AI_LEVELS[cfg.aiDifficulty||'Soldier']?.bonusGold||0):0),alive:true,observer:false,influence:0,kind:cfg.kind||'Human',aiDifficulty:cfg.aiDifficulty||'Soldier',commanderClass:cls,commanderName:cmd.name});});}
function placeStarts(){let starts=[{x:1,y:1},{x:state.w-2,y:state.h-2},{x:state.w-2,y:1},{x:1,y:state.h-2},{x:Math.floor(state.w/2),y:1},{x:Math.floor(state.w/2),y:state.h-2},{x:1,y:Math.floor(state.h/2)},{x:state.w-2,y:Math.floor(state.h/2)}];
 state.players.forEach((p,i)=>{let pos=nearestOpen(starts[i]); for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){let x=pos.x+dx,y=pos.y+dy;if(x>=0&&y>=0&&x<state.w&&y<state.h&&Math.abs(dx)+Math.abs(dy)<=3&&tile(x,y).t==='water')tile(x,y).t='plains';} let home=tile(pos.x,pos.y); home.t='roads'; home.s='city'; home.owner=p.id; addUnit('Commander',p.id,pos.x,pos.y,{commanderClass:p.commanderClass}); let near=nearestOpen({x:pos.x+1,y:pos.y}); addUnit('Infantry',p.id,near.x,near.y); let near2=nearestOpen({x:pos.x,y:pos.y+1}); addUnit(i%2?'Riflemen':'Pikemen',p.id,near2.x,near2.y); let town=nearestOpen({x:pos.x+(pos.x<state.w/2?3:-3),y:pos.y+(pos.y<state.h/2?2:-2)}); tile(town.x,town.y).t='roads'; tile(town.x,town.y).s='town'; tile(town.x,town.y).owner=null;});
 let center=nearestOpen({x:Math.floor(state.w/2),y:Math.floor(state.h/2)}); tile(center.x,center.y).t='hills'; tile(center.x,center.y).s='fortress'; tile(center.x,center.y).owner=null; for(let x=1;x<state.w-1;x++) if(tile(x,Math.floor(state.h/2)).t!=='water') tile(x,Math.floor(state.h/2)).t='roads'; for(let y=1;y<state.h-1;y++) if(tile(Math.floor(state.w/2),y).t!=='water') tile(Math.floor(state.w/2),y).t='roads'; }
function nearestOpen(p){for(let r=0;r<8;r++)for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){let x=Math.max(0,Math.min(state.w-1,p.x+dx)),y=Math.max(0,Math.min(state.h-1,p.y+dy)); if(tile(x,y).t!=='water'&&!unitAt(x,y)) return {x,y};} return {x:0,y:0}}
function addUnit(type,owner,x,y,extra={}){let b=UNITS[type]; state.units.push({id:state.nextUnitId++,type,owner,x,y,hp:b.hp,maxHp:b.hp,xp:0,veteran:0,moved:false,acted:false,squadMax:b.squad||1,...extra});}
function startTurn(){let p=player(); state.turnEvents=[]; if(!p.alive){p.influence+=2; log(`${p.name} observes from exile and gains 2 Influence.`); state.turnEvents.push(`${p.name} gains 2 Observer Influence.`); return;}
 let income=0, breakdown=[]; state.map.forEach(t=>{if(t.owner===p.id&&t.s){income+=STRUCTS[t.s].income;breakdown.push(`${STRUCTS[t.s].name} +${STRUCTS[t.s].income}`)}}); p.gold+=income; p.influence+=p.observer?2:0; state.lastIncome=income; state.lastIncomeBreakdown=breakdown;
 state.units.filter(u=>u.owner===p.id&&u.hp>0).forEach(u=>{u.moved=false;u.acted=false; let before=u.hp; applyAuraHeal(u); if(u.hp>before)queueFx(u.x,u.y,`+${u.hp-before}`,'heal'); if(canCapture(u)){let tt=tile(u.x,u.y); if(tt.s&&tt.owner!==p.id){tt.owner=p.id; log(`${p.name} captured ${STRUCTS[tt.s].name} at ${u.x},${u.y}.`); state.turnEvents.push(`Captured ${STRUCTS[tt.s].name} at ${u.x},${u.y}.`)}}}); log(`${p.name} begins turn and earns ${income} gold.`); state.turnEvents.unshift(`Income: +${income} gold${breakdown.length?' — '+breakdown.join(', '):''}`); setTimeout(()=>showTurnToast(`${p.name}: +${income} gold`),80); sfx('turn'); }
function applyAuraHeal(u){let aura=getAuraFor(u.owner,u); if(aura){u.hp=Math.min(u.maxHp,u.hp+aura.heal)}}
function getAuraFor(owner,u){let cmd=state.units.find(c=>c.owner===owner&&c.type==='Commander'&&c.hp>0); if(!cmd||dist(cmd,u)>3||u.id===cmd.id) return null; return COMMANDERS[state.players[owner].commanderClass];}
function endTurn(){if(!state)return; if(state.aiRunning&&player().kind!=='AI')return; selected=null; highlights=[]; checkDefeats(); let outgoing=player(); let summary={from:outgoing.name,turn:state.turn,events:[...(state.turnEvents||[])],next:''}; let winner=state.players.filter(p=>p.alive).length===1?state.players.find(p=>p.alive):null; if(winner){log(`🏆 ${winner.name} wins the War of Brass!`); startMusic('victory'); sfx('win'); render(); alert(`${winner.name} wins!`); return;} do{state.current=(state.current+1)%state.players.length; if(state.current===0)state.turn++; startTurn();}while(!player().alive && state.players.some(p=>p.alive)); summary.next=player().name; lastTurnSummary=summary; state.lastTurnSummary=summary; setThemeForCurrent(); log(`Turn handoff: ${summary.from} should save and post the file for ${summary.next}.`); render(); maybeRunAI();}
function checkDefeats(){state.players.forEach(p=>{if(!p.alive)return; let cmdAlive=state.units.some(u=>u.owner===p.id&&u.type==='Commander'&&u.hp>0); let cities=state.map.some(t=>t.owner===p.id&&t.s==='city'); if(!cmdAlive&&!cities){p.alive=false;p.observer=true;p.influence+=3;log(`${p.name} is defeated and becomes an Observer with 3 Influence.`)}})}
function render(){if(!state)return; $('turnBadge').textContent=`Turn ${state.turn} — ${player().name}${player().observer?' (Observer)':player().kind==='AI'?' (AI)':''}`; $('turnBadge').classList.toggle('turnBadgeAI',player().kind==='AI'); $('versionBadge').textContent=`Build ${VERSION}`; $('saveBadge').textContent=`${state.players.length}P · ${state.players.filter(p=>p.kind==='AI').length} AI · ${state.weather||'Clear'} · Save for ${player().name}`; renderMap(); renderPanels(); renderLog();}
function visibleSet(pid){let set=new Set(); state.units.filter(u=>u.owner===pid&&u.hp>0).forEach(u=>{for(let y=u.y-4;y<=u.y+4;y++)for(let x=u.x-4;x<=u.x+4;x++){if(x>=0&&y>=0&&x<state.w&&y<state.h&&Math.abs(x-u.x)+Math.abs(y-u.y)<=4)set.add(`${x},${y}`)}}); state.map.forEach(t=>{if(t.owner===pid&&t.s){for(let y=t.y-2;y<=t.y+2;y++)for(let x=t.x-2;x<=t.x+2;x++)if(x>=0&&y>=0&&x<state.w&&y<state.h)set.add(`${x},${y}`)}}); return set;}
function renderMap(){let map=$('map');map.style.gridTemplateColumns=`repeat(${state.w}, var(--tile))`;map.innerHTML='';let vis=player().alive?visibleSet(state.current):new Set(state.map.map(t=>`${t.x},${t.y}`));
 state.map.forEach(t=>{let seen=vis.has(`${t.x},${t.y}`);let div=document.createElement('div');div.dataset.x=t.x;div.dataset.y=t.y;div.className=`tile ${seen?TERRAIN[t.t].name.toLowerCase():''} ${seen?t.t:''}`; if(!seen)div.classList.add('hidden'); if(lastTile&&lastTile.x===t.x&&lastTile.y===t.y)div.classList.add('selectedTile'); if(seen){div.innerHTML=tileArt(t)+`<span class="coord">${TERRAIN[t.t].icon}</span><span class="terrainBadge">D${terrainDefenseAt(t)}</span>`; if(t.s){div.classList.add(t.s);div.innerHTML+=structureArt(t.s,t.owner)} if(t.owner!==null)div.innerHTML+=`<span class="ownerDot" style="background:${state.players[t.owner].color}"></span>`;}
 let h=highlights.find(h=>h.x==t.x&&h.y==t.y); if(h)div.classList.add(h.type+'Mark'); let u=unitAt(t.x,t.y); if(u&&seen){let base=UNITS[u.type]; let ready=u.owner===state.current&&!u.moved&&!u.acted&&player().alive; let aura=getAuraFor(u.owner,u); div.classList.add(...base.class.split(' ')); if(aura)div.classList.add('auraMark'); div.innerHTML+=`<div class="unit ${ready?'ready':'exhausted'} ${u.type==='Commander'?'commander':''}" data-unit-id="${u.id}" style="--team:${state.players[u.owner].color};border-color:${state.players[u.owner].color}" title="${u.type}">${unitSprite(u,'asset-sprite',ready)}</div><div class="hpbar"><div class="hpfill" style="width:${Math.max(0,u.hp/u.maxHp*100)}%"></div></div>`;}
 div.onclick=()=>tileClick(t.x,t.y); map.appendChild(div);});}
function assetSlug(name){return String(name).toLowerCase().replaceAll(' ','_').replaceAll('-','_');}
function ownerAssetIndex(owner){return Math.max(0,Math.min(7,owner||0));}
function commanderAssetSlug(cls){return assetSlug(cls);}
function unitSprite(u,cls='asset-sprite',animated=false){let owner=ownerAssetIndex(u.owner); let base=u.type==='Commander'?`assets/commanders/p${owner}/${commanderAssetSlug(u.commanderClass||state.players[u.owner].commanderClass)}`:`assets/units/p${owner}/${assetSlug(u.type)}`; if(animated&&cls==='asset-sprite')return `<span class="unitAnim"><img class="unitFrame frameA" src="${base}_f1.png" alt="${u.type}" loading="eager"><img class="unitFrame frameB" src="${base}_f2.png" alt="${u.type}" loading="eager"></span>`; return `<img class="${cls} pngSprite" src="${base}.png" alt="${u.type}" loading="eager">`; }
function battleUnitSrc(u){let owner=ownerAssetIndex(u.owner); return u.type==='Commander'?`assets/commanders/p${owner}/${commanderAssetSlug(u.commanderClass||state.players[u.owner].commanderClass)}_battle.png`:`assets/units/p${owner}/${assetSlug(u.type)}_battle.png`;}
function typeSprite(type,owner=state?state.current:0,cls='miniSprite'){let fake={type,owner,commanderClass:state&&state.players[owner]?state.players[owner].commanderClass:'Steam Marshal'};return unitSprite(fake,cls)}
function commanderClassSprite(cls,owner=state?state.current:0,svgCls='miniSprite'){return `<img class="${svgCls} pngSprite" src="assets/commanders/p${ownerAssetIndex(owner)}/${commanderAssetSlug(cls)}.png" alt="${cls}" loading="eager">`;}
function terrainMask(t){let mask=0, type=t.t; [[0,-1,1],[1,0,2],[0,1,4],[-1,0,8]].forEach(([dx,dy,bit])=>{let x=t.x+dx,y=t.y+dy;if(x>=0&&y>=0&&x<state.w&&y<state.h){let nt=tile(x,y); if(nt.t===type||(type==='roads'&&nt.s))mask|=bit;}}); return mask;}
function tileArt(t){let slug=assetSlug(t.t); if(['roads','water','forest','hills','mountains'].includes(t.t)){return `<img class="tilePng" src="assets/tiles/${slug}_${terrainMask(t)}.png" alt="${t.t}" loading="eager">`;} return `<img class="tilePng" src="assets/tiles/${slug}.png" alt="${t.t}" loading="eager">`; }
function structureArt(s,owner){let idx=owner!==null?ownerAssetIndex(owner):0; return `<img class="structureSprite structPng" src="assets/structures/p${idx}/${assetSlug(s)}.png" alt="${STRUCTS[s].name}" loading="eager">`;}
function unitIcon(u){return unitSprite(u,'miniSprite');}
function tileClick(x,y){if(!state)return; if(player().kind==='AI'){showTurnToast(`${player().name} is computer controlled.`); return;} enableAudio(); lastTile={x,y}; let u=unitAt(x,y); let h=highlights.find(h=>h.x==x&&h.y==y); if(h&&selected){ if(h.type==='move'){selected.x=x;selected.y=y;selected.moved=true;log(`${player().name}'s ${selected.type} moves to ${x},${y}.`); sfx('move'); selected=null; highlights=[]; render(); return;} if(h.type==='attack'){attack(selected,u); selected=null; highlights=[]; return;} }
 if(u&&u.owner===state.current&&player().alive&&!u.moved&&!u.acted){selected=u; makeHighlights(u); render(); renderPanels(); return;}
 selected=u||null; highlights=[]; render(); renderPanels();}
function makeHighlights(u){highlights=[]; for(let y=0;y<state.h;y++)for(let x=0;x<state.w;x++){let d=Math.abs(x-u.x)+Math.abs(y-u.y); if(d>0&&d<=UNITS[u.type].mv&&canEnter(u,x,y))highlights.push({x,y,type:'move'}); let enemy=unitAt(x,y); if(enemy&&enemy.owner!==u.owner&&d<=UNITS[u.type].range)highlights.push({x,y,type:'attack'});} }
function canEnter(u,x,y){let tt=tile(x,y), occupied=unitAt(x,y); if(occupied)return false; if(tt.t==='water' && !UNITS[u.type].tags.includes('air') && !UNITS[u.type].tags.includes('gyro'))return false; if(tt.t==='mountains' && !UNITS[u.type].tags.includes('air') && !UNITS[u.type].tags.includes('gyro') && UNITS[u.type].mv<4)return false; return true;}
function canCapture(u){return UNITS[u.type].capture}
function attack(a,d){if(!a||!d||a.owner===d.owner)return; let preA={...a}, preD={...d}; let detail=calcDamageDetail(a,d); let dmg=detail.damage; d.hp-=dmg; a.acted=true; a.moved=true; animateCombat(preA,preD,detail,false); log(`${state.players[a.owner].name}'s ${a.type} hits ${d.type} for ${dmg}${detail.terrainReduction>0?` (${detail.coverName} absorbed ${detail.terrainReduction})`:''}.`); if(state.turnEvents)state.turnEvents.push(`${a.type} attacked ${d.type} for ${dmg}.`); let defenderDestroyed=d.hp<=0; if(defenderDestroyed){log(`${d.type} destroyed.`); a.xp+=35; sfx(detail.heavy?'heavy':'hit'); setTimeout(()=>{removeDead(); checkDefeats(); vetCheck(a); render();}, animDelay()); return;} if(dist(a,d)<=UNITS[d.type].range){let cdetail=calcDamageDetail(d,a); let cd=Math.max(3,Math.floor(cdetail.damage*0.55)); a.hp-=cd; animateCombat(preD,preA,{...cdetail,damage:cd},true); log(`${d.type} counterattacks for ${cd}${cdetail.terrainReduction>0?` (${cdetail.coverName} absorbed ${cdetail.terrainReduction})`:''}.`); if(a.hp<=0)log(`${a.type} destroyed by counterattack.`); d.xp+=10; } a.xp+=20; sfx(detail.heavy?'heavy':'hit'); setTimeout(()=>{vetCheck(a); removeDead(); checkDefeats(); render();}, animDelay()); render();}
function calcDamage(a,d){return calcDamageDetail(a,d).damage}
function terrainDefenseAt(t){if(!t)return 0; let val=TERRAIN[t.t].def||0; if(t.s==='town')val=Math.max(val,2); if(t.s==='city')val=Math.max(val,3); if(t.s==='fortress')val=Math.max(val,4); return val;}
function calcDamageDetail(a,d){let ab=UNITS[a.type], db=UNITS[d.type], hpScale=Math.max(.25,a.hp/a.maxHp), mult=1, counter=''; for(let at of ab.tags){if(COUNTERS[at]) for(let dt of db.tags) if(COUNTERS[at][dt]&&COUNTERS[at][dt]>mult){mult=COUNTERS[at][dt];counter=`${at} beats ${dt}`;}}
 let targetTile=tile(d.x,d.y), auraA=getAuraFor(a.owner,a), auraD=getAuraFor(d.owner,d); let terrainDef=terrainDefenseAt(targetTile); if(ab.tags.includes('air')||ab.tags.includes('gyro')) terrainDef=Math.floor(terrainDef*.5); let atk=ab.atk+a.veteran*4+(auraA?auraA.atk:0); let baseDef=db.def+d.veteran*3+(auraD?auraD.def:0); let terrainReduction=Math.max(0,Math.round(terrainDef*.9)); let raw=(atk*hpScale*mult)-(baseDef*.65)-(terrainDef*.9)+Math.floor(rng()*7); let damage=Math.max(5,Math.floor(raw)); return {damage,atk,baseDef,terrainDef,terrainReduction,counter,mult,coverName:targetTile.s?STRUCTS[targetTile.s].name:TERRAIN[targetTile.t].name,heavy:ab.tags.includes('artillery')||ab.tags.includes('tank')||a.type==='Commander'};}
function combatPreview(a,d){let detail=calcDamageDetail({...a},{...d}); let counter=dist(a,d)<=UNITS[d.type].range; let cd=counter?Math.max(3,Math.floor(calcDamageDetail({...d},{...a}).damage*.55)):0; return {detail,counter,cd,afterD:Math.max(0,d.hp-detail.damage),afterA:Math.max(0,a.hp-cd)};}
function animDelay(){let v=$('animSpeed')?.value||'Normal'; return v==='Off'?0:v==='Fast'?260:700}
function tileToPixels(x,y){let el=document.querySelector(`.tile[data-x=\"${x}\"][data-y=\"${y}\"]`); if(el)return {left:el.offsetLeft+el.offsetWidth/2,top:el.offsetTop+el.offsetHeight/2}; return {left:x*53+26,top:y*53+26}}
function queueFx(x,y,text,cls='damage'){setTimeout(()=>floatingText(x,y,text,cls),80)}
function floatingText(x,y,text,cls='damage'){let wrap=$('mapWrap'); if(!wrap)return; let pos=tileToPixels(x,y), el=document.createElement('div'); el.className=`battleFx ${cls}`; el.style.left=(pos.left+10)+'px'; el.style.top=(pos.top+6)+'px'; el.textContent=text; wrap.appendChild(el); setTimeout(()=>el.remove(),850)}
function burstFx(x,y,heavy=false){let wrap=$('mapWrap'); if(!wrap)return; let pos=tileToPixels(x,y), el=document.createElement('div'); el.className=`battleFx burst ${heavy?'heavy':''}`; el.style.left=pos.left+'px'; el.style.top=pos.top+'px'; wrap.appendChild(el); setTimeout(()=>el.remove(),600)}

function battleTerrainKey(u){let tt=tile(u.x,u.y); return tt.s?tt.s:tt.t;}
function battleViewSetting(){return $('battleView')?.value||'On';}
function hideBattleView(){let ov=$('battleOverlay'); if(ov)ov.classList.remove('show'); setThemeForCurrent();}
function commanderPortraitSrc(cls){return `assets/commanders/portraits/${commanderAssetSlug(cls)}.png`;}
function squadMax(type){return UNITS[type]?.squad||1;}
function squadCount(u,hp=u.hp){let m=u.squadMax||squadMax(u.type); if(m<=1)return hp>0?1:0; return Math.max(0,Math.min(m,Math.ceil(Math.max(0,hp)/u.maxHp*m)));}
function machineLike(u){return ['Artillery','Steam Tank','Airship','Gyrocopter'].includes(u.type);}
function renderBattleSquad(el,u,beforeHp,afterHp,side){if(!el)return; let before=squadCount(u,beforeHp), after=squadCount(u,afterHp), lost=Math.max(0,before-after); let src=battleUnitSrc(u), cls=machineLike(u)?'machine':''; let hero=u.type==='Commander'; let html=''; for(let i=0;i<before;i++){let casualty=i>=after; html+=`<img class="battleMember ${hero?'hero':(before<=5?'large':'')} ${cls} ${casualty?'pendingCasualty':''}" src="${src}" alt="${u.type}">`;} el.innerHTML=html; el.classList.remove('attack','hit'); void el.offsetWidth; if(side==='attacker')el.classList.add('attack'); else el.classList.add('hit'); setTimeout(()=>{el.querySelectorAll('.pendingCasualty').forEach(x=>x.classList.add('casualty'));},360);}
function showBattleView(a,d,detail,isCounter){let mode=battleViewSetting(); if(mode==='Off')return; let ov=$('battleOverlay'), box=$('battleBox'); if(!ov||!box)return; startMusic('battle'); box.classList.toggle('battleFast',mode==='Fast'); $('battleBg').style.backgroundImage=`url(assets/battle_backgrounds/${battleTerrainKey(d)}.png)`; let ap=state.players[a.owner], dp=state.players[d.owner]; $('battleAttackerName').textContent=`${ap.name} ${a.type}`; $('battleDefenderName').textContent=`${dp.name} ${d.type}`; $('battleAttackerMeta').textContent=`${isCounter?'Counterattack':'Attack'} · HP ${Math.max(0,a.hp)}/${a.maxHp} · Squad ${squadCount(a)}/${squadMax(a.type)}`; $('battleDefenderMeta').textContent=`${detail.coverName} Cover +${detail.terrainDef}${detail.counter?' · '+detail.counter:''} · Squad ${squadCount(d)}/${squadMax(d.type)}`; $('battleAttackerHp').style.width=Math.max(0,Math.min(100,a.hp/a.maxHp*100))+'%'; $('battleDefenderHp').style.width=Math.max(0,Math.min(100,d.hp/d.maxHp*100))+'%'; $('battleAttackerImg').src=battleUnitSrc(a); $('battleDefenderImg').src=battleUnitSrc(d); let attPortrait=$('battleAttackerPortrait'), defPortrait=$('battleDefenderPortrait'); if(a.type==='Commander'){attPortrait.src=commanderPortraitSrc(ap.commanderClass);attPortrait.style.display='block'}else attPortrait.style.display='none'; if(d.type==='Commander'){defPortrait.src=commanderPortraitSrc(dp.commanderClass);defPortrait.style.display='block'}else defPortrait.style.display='none'; renderBattleSquad($('battleAttackerSquad'),a,a.hp,a.hp,'attacker'); renderBattleSquad($('battleDefenderSquad'),d,d.hp,Math.max(0,d.hp-detail.damage),'defender'); $('battleMsg').textContent=`${isCounter?'Counterattack!':'Strike!'} ${detail.coverName}${detail.terrainReduction>0?' absorbs '+detail.terrainReduction:' provides no cover'} · casualties visible.`; let fx=$('battleFxImg'), dmg=$('battleDamage'); fx.src=detail.heavy?'assets/effects/explosion.png':(a.type==='Mage'||a.type==='Commander'&&ap.commanderClass==='Archmage'?'assets/effects/spell_burst.png':'assets/effects/hit_burst.png'); fx.style.left='calc(50% + 125px)'; fx.style.top='120px'; fx.style.display='block'; dmg.textContent='-'+detail.damage; dmg.style.left='calc(50% + 155px)'; dmg.style.top='118px'; dmg.style.display='block'; ov.classList.add('show'); let closeDelay=mode==='Fast'?900:1850; setTimeout(()=>{fx.style.display='none';dmg.style.display='none';hideBattleView();},closeDelay);}

function animateCombat(a,d,detail,isCounter){showBattleView(a,d,detail,isCounter);let speed=$('animSpeed')?.value||'Normal'; if(speed==='Off')return; setTimeout(()=>{let attacker=document.querySelector(`[data-unit-id="${a.id}"]`); if(attacker){attacker.classList.add('attackLunge'); setTimeout(()=>attacker.classList.remove('attackLunge'),420)}},isCounter?320:40); setTimeout(()=>{let defender=document.querySelector(`[data-unit-id="${d.id}"]`); if(defender){defender.classList.add('hitFlash'); setTimeout(()=>defender.classList.remove('hitFlash'),420)} burstFx(d.x,d.y,detail.heavy); floatingText(d.x,d.y,`${isCounter?'Counter ':''}-${detail.damage}`,'damage'); if(detail.terrainReduction>0)floatingText(d.x,d.y,`Cover -${detail.terrainReduction}`,'terrain'); if(detail.counter)floatingText(d.x,d.y,'Counter bonus','counter'); if(detail.heavy){let m=$('map'); if(m){m.classList.add('shake'); setTimeout(()=>m.classList.remove('shake'),260)}}},isCounter?520:220);}
function removeDead(){state.units=state.units.filter(u=>u.hp>0)} function vetCheck(u){if(u.xp>=100){u.xp-=100;u.veteran++;u.maxHp+=8;u.hp+=8;log(`${u.type} becomes Veteran ${u.veteran}.`)}}
function renderPanels(){let pHtml=''; state.players.forEach((p,i)=>{let owned=state.map.filter(t=>t.owner===p.id&&t.s).length; let income=state.map.filter(t=>t.owner===p.id&&t.s).reduce((s,t)=>s+STRUCTS[t.s].income,0); pHtml+=`<div class="playerLine ${p.kind==='AI'?'ai':'human'}"><span><span class="swatch" style="background:${p.color}"></span>${i===state.current?'➤ ':''}${p.name}</span><span>${p.kind}${p.kind==='AI'?` · ${p.aiDifficulty}`:''} · ${p.alive?'Alive':'Observer'} · ${p.gold}g · +${income}/turn · ${owned} sites</span></div>`}); $('playerInfo').innerHTML=pHtml+(player().kind==='AI'&&state.aiRunning?'<div class="aiThinking">AI turn in progress — the brass engines are thinking...</div>':'');
 let u=selected; $('unitInfo').innerHTML=u?unitCard(u):'Select a unit.'; renderTerrainInfo(); renderHandoffPanel(); let cmd=state.units.find(c=>c.owner===state.current&&c.type==='Commander'); let cp=player(); let danger=cmd&&state.units.some(e=>e.owner!==state.current&&e.hp>0&&dist(e,cmd)<=UNITS[e.type].range+1); if(danger&&cp.kind==='Human')startMusic('danger'); $('commanderInfo').innerHTML=cmd?`<div class="card"><img class="portraitWide" src="${commanderPortraitSrc(cp.commanderClass)}" alt="${cp.commanderName}"><div class="commanderName">${cp.commanderName}</div><b>${commanderClassSprite(cp.commanderClass,state.current,'miniSprite')} ${cp.commanderClass}</b><br>${COMMANDERS[cp.commanderClass].desc}<br>HP ${cmd.hp}/${cmd.maxHp}<br>Aura radius: 3<br><span class="pill good">Aura: +${COMMANDERS[cp.commanderClass].atk} Atk / +${COMMANDERS[cp.commanderClass].def} Def / +${COMMANDERS[cp.commanderClass].heal} heal</span>${cp.kind==='AI'?`<span class="pill difficultyPill">AI ${cp.aiDifficulty}</span>`:''}${danger?'<div class="warnBox">Commander danger: enemies are near attack range.</div>':''}</div>`:`<span class="danger">Commander dead.</span>`; renderRecruit(); renderObserver();}
function renderTerrainInfo(){if(!$('terrainInfo'))return; if(!state){$('terrainInfo').textContent='No game.';return;} let t=lastTile?tile(lastTile.x,lastTile.y):null; let html=''; if(t){html+=`<div class="card"><b>${TERRAIN[t.t].name}</b> at ${t.x},${t.y}<br>Move cost: ${TERRAIN[t.t].move} · Defense cover: +${terrainDefenseAt(t)}${t.s?`<br>Structure: ${STRUCTS[t.s].name} · Income ${STRUCTS[t.s].income}g · Owner ${t.owner!==null?state.players[t.owner].name:'Neutral'}`:''}</div>`;} if(selected){let targets=highlights.filter(h=>h.type==='attack').map(h=>unitAt(h.x,h.y)).filter(Boolean); if(targets.length){let target=lastTile?unitAt(lastTile.x,lastTile.y):targets[0]; if(target&&target.owner!==selected.owner){let p=combatPreview(selected,target); html+=`<div class="previewBox"><b>Combat Preview</b><br>${selected.type} → ${target.type}<br>Expected damage: ${p.detail.damage} (${p.detail.coverName} cover ${p.detail.terrainDef})<br>${p.detail.counter?`Matchup bonus: ${p.detail.counter}<br>`:''}${p.counter?`Counterattack warning: about ${p.cd} damage<br>`:'No counterattack expected.<br>'}After exchange: target ${p.afterD}/${target.maxHp}, attacker ${p.afterA}/${selected.maxHp}</div>`;}}} html+=`<div class="terrainTable"><b>Cover</b><b>Move</b><b>Def</b>${Object.entries(TERRAIN).map(([k,v])=>`<span>${v.name}</span><span>${v.move}</span><span>+${v.def}</span>`).join('')}<span>Town</span><span>—</span><span>+2</span><span>City</span><span>—</span><span>+3</span><span>Fortress</span><span>—</span><span>+4</span></div>`; $('terrainInfo').innerHTML=html||'Select a tile or attack target.';}
function suggestedSaveName(){if(!state)return 'Iron_Kingdoms_War_of_Brass.json'; return `Iron_Kingdoms_War_of_Brass_${VERSION}_Turn_${state.turn}_${player().name.replace(/\s+/g,'_')}.json`;}
function renderHandoffPanel(){if(!$('handoffPanel')||!state)return; let living=state.players.filter(p=>p.alive).map(p=>`${p.name}${p.kind==='AI'?' [AI]':''}`).join(', '); let obs=state.players.filter(p=>p.observer).map(p=>p.name).join(', ')||'None'; let summary=state.lastTurnSummary||lastTurnSummary; let msg=player().kind==='AI'?'Computer-controlled kingdom: this turn resolves automatically.':'Discord handoff: Load the latest save before acting. After End Turn, save and post the JSON.'; $('handoffPanel').innerHTML=`<div><b>${msg}</b><br>Current player is <b style="color:${player().color}">${player().name}</b> ${player().kind==='AI'?`<span class="pill difficultyPill">${player().aiDifficulty}</span>`:''}.</div><div><div class="saveName">${suggestedSaveName()}</div><span class="small">Alive: ${living}<br>Observers: ${obs}${summary?`<br>Last handoff: ${summary.from} → ${summary.next}`:''}</span></div>`;}
function counterHints(type){let tags=UNITS[type].tags, beats=[]; for(let at of tags){if(COUNTERS[at]) beats.push(...Object.keys(COUNTERS[at]).map(k=>k));} let threatened=[]; Object.entries(COUNTERS).forEach(([atk,defs])=>{for(let dt of tags)if(defs[dt])threatened.push(atk)}); return {beats:[...new Set(beats)].join(', ')||'none',threatened:[...new Set(threatened)].join(', ')||'none'};}
function unitCard(u){let b=UNITS[u.type], aura=getAuraFor(u.owner,u), hints=counterHints(u.type), tt=tile(u.x,u.y); return `<div class="card"><b style="color:${state.players[u.owner].color}">${unitIcon(u)} ${u.type}</b><br>Owner: ${state.players[u.owner].name}<div class="statGrid"><span>HP ${u.hp}/${u.maxHp}</span><span>Squad ${squadCount(u)}/${squadMax(u.type)}</span><span>Move ${b.mv}</span><span>Atk ${b.atk}</span><span>Def ${b.def}</span><span>Range ${b.range}</span><span>Vet ${u.veteran}</span><span>XP ${u.xp}/100</span><span>${u.moved||u.acted?'Exhausted':'Ready'}</span></div><div class="rangeLine"><span style="width:${Math.min(100,u.xp)}%"></span></div><span class="pill">Cover +${terrainDefenseAt(tt)}</span><span class="squadBadge">${squadMax(u.type)>1?'Formation':'Hero'} count tracks HP</span>${aura?`<span class="pill good">Aura boosted</span>`:''}${b.capture?`<span class="pill">Can capture</span>`:''}<br><span class="small">Strong vs: ${hints.beats}<br>Watch out for: ${hints.threatened}</span></div>`}
function renderRecruit(){let tt=selected?tile(selected.x,selected.y):null; let can=tt&&tt.s==='city'&&tt.owner===state.current&&player().alive; $('recruitInfo').innerHTML=can?`Recruiting at city ${tt.x},${tt.y}. Gold: ${player().gold}`:'Select one of your cities to recruit.'; let html=''; if(can){Object.keys(UNITS).filter(k=>k!=='Commander').forEach(type=>{let b=UNITS[type]; html+=`<button class="recruitBtn" ${player().gold<b.cost?'disabled':''} onclick="recruit('${type}',${tt.x},${tt.y})">${typeSprite(type,state.current,'miniSprite')} ${type} — ${b.cost}g <span class="small">HP${b.hp} M${b.mv} A${b.atk} D${b.def} R${b.range}</span></button>`})} $('recruitMenu').innerHTML=html;}
function recruit(type,x,y){let p=player(), b=UNITS[type]; if(p.gold<b.cost)return; let spots=[[x+1,y],[x-1,y],[x,y+1],[x,y-1],[x,y]]; let pos=spots.find(s=>s[0]>=0&&s[1]>=0&&s[0]<state.w&&s[1]<state.h&&!unitAt(s[0],s[1])&&canEnter({type},s[0],s[1])); if(!pos){alert('No open adjacent tile.');return;} p.gold-=b.cost; addUnit(type,p.id,pos[0],pos[1]); let nu=state.units[state.units.length-1]; nu.moved=true;nu.acted=true; log(`${p.name} recruits ${type}.`); render();}
function renderObserver(){let p=player(); if(!p.observer){$('observerInfo').innerHTML='Observer powers unlock after elimination.';$('observerMenu').innerHTML='';return;} $('observerInfo').innerHTML=`${p.name} has ${p.influence} Influence Tokens.`; const powers=[['Supply Drop',3,'Heal all units of a chosen living player by 10.'],['Sabotage',4,'Damage a random enemy unit of the current leading player.'],['Weather Shift',3,'Toggle rough weather. Roads less useful; air slightly weaker this round.'],['Forced March',3,'Ready one random exhausted unit of the weakest living player.'],['Spy Network',2,'Reveal entire map for observers/current save review.'],['Mercenary Contract',5,'Spawn Infantry for the weakest living player near a city.']]; $('observerMenu').innerHTML=powers.map(q=>`<button class="recruitBtn" ${p.influence<q[1]?'disabled':''} onclick="observerPower('${q[0]}',${q[1]})">${q[0]} — ${q[1]}☼<br><span class="small">${q[2]}</span></button>`).join('');}
function weakestLiving(){let living=state.players.filter(p=>p.alive); return living.sort((a,b)=>state.units.filter(u=>u.owner===a.id).length-state.units.filter(u=>u.owner===b.id).length)[0];}
function observerPower(name,cost){let p=player(); if(!p.observer||p.influence<cost)return; p.influence-=cost; let target=weakestLiving(); if(name==='Supply Drop')state.units.filter(u=>u.owner===target.id).forEach(u=>{let before=u.hp;u.hp=Math.min(u.maxHp,u.hp+10); if(u.hp>before)queueFx(u.x,u.y,`+${u.hp-before}`,'heal')});
 if(name==='Sabotage'){let lead=state.players.filter(x=>x.alive).sort((a,b)=>b.gold-a.gold)[0]; let us=state.units.filter(u=>u.owner===lead.id&&u.type!=='Commander'); if(us.length){let u=us[Math.floor(rng()*us.length)];u.hp-=22;log(`Observer sabotage damages ${lead.name}'s ${u.type}.`);removeDead();}}
 if(name==='Weather Shift'){state.weather=state.weather==='Clear'?'Storm':'Clear'; log(`Observers shift the weather: ${state.weather}.`)}
 if(name==='Forced March'){let us=state.units.filter(u=>u.owner===target.id&&(u.moved||u.acted)); if(us.length){let u=us[Math.floor(rng()*us.length)];u.moved=false;u.acted=false;log(`${target.name}'s ${u.type} is readied by Forced March.`)}}
 if(name==='Spy Network'){log(`${p.name} activates Spy Network. Use the save/review knowledge carefully.`)}
 if(name==='Mercenary Contract'){let city=state.map.find(t=>t.owner===target.id&&t.s==='city'); if(city){let pos=nearestOpen(city);addUnit('Infantry',target.id,pos.x,pos.y);}}
 log(`${p.name} spends ${cost} Influence on ${name}.`); render();}

function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function maybeRunAI(){if(!state)return; let p=player(); if(!p||!p.alive||p.kind!=='AI'||state.aiRunning)return; state.aiRunning=true; selected=null; highlights=[]; setThemeForCurrent(); render(); showTurnToast(`${p.name} (${p.aiDifficulty}) is taking its turn...`); setTimeout(()=>runAiTurn(),450);}
async function runAiTurn(){if(!state||player().kind!=='AI'){state.aiRunning=false;return;} let p=player(), level=AI_LEVELS[p.aiDifficulty]||AI_LEVELS.Soldier; log(`${p.name} AI (${p.aiDifficulty}) begins planning.`); aiRecruit(p,level); render(); await sleep(300); let units=state.units.filter(u=>u.owner===p.id&&u.hp>0&&!u.acted).sort((a,b)=>(a.type==='Commander')-(b.type==='Commander')); let limit=0; for(let u of units){if(!state||player().id!==p.id||!u||u.hp<=0)continue; aiActUnit(u,level); render(); await sleep(Math.max(220,animDelay()+260)); if(++limit>20)break;} state.aiRunning=false; log(`${p.name} AI ends turn.`); await sleep(300); endTurn();}
function aiRecruit(p,level){let cities=state.map.filter(t=>t.owner===p.id&&t.s==='city'); for(let c of cities){let choice=aiChooseRecruit(p,level); if(choice)aiRecruitAt(p,c,choice);}}
function aiChooseRecruit(p,level){let roster=['Infantry','Pikemen','Riflemen','Cavalry']; if(level.rank>=2)roster.push('Mage','Assassin'); if(level.rank>=3)roster.push('Artillery','Gyrocopter'); if(level.rank>=4)roster.push('Steam Tank','Airship'); let enemies=state.units.filter(u=>u.owner!==p.id&&u.hp>0), air=enemies.filter(u=>UNITS[u.type].tags.includes('air')).length, tanks=enemies.filter(u=>UNITS[u.type].tags.includes('tank')).length, cav=enemies.filter(u=>UNITS[u.type].tags.includes('cavalry')).length; let pref=air?'Riflemen':tanks?'Artillery':cav?'Pikemen':roster[Math.floor(rng()*roster.length)]; if(UNITS[pref]&&p.gold>=UNITS[pref].cost)return pref; return roster.filter(x=>p.gold>=UNITS[x].cost).sort((a,b)=>UNITS[b].cost-UNITS[a].cost)[0];}
function aiRecruitAt(p,c,type){let b=UNITS[type]; if(!b||p.gold<b.cost)return; let spots=[[c.x+1,c.y],[c.x-1,c.y],[c.x,c.y+1],[c.x,c.y-1],[c.x,c.y]]; let pos=spots.find(s=>s[0]>=0&&s[1]>=0&&s[0]<state.w&&s[1]<state.h&&!unitAt(s[0],s[1])&&canEnter({type},s[0],s[1])); if(!pos)return; p.gold-=b.cost; addUnit(type,p.id,pos[0],pos[1]); let nu=state.units[state.units.length-1]; nu.moved=true;nu.acted=true; log(`${p.name} recruits ${type}.`);}
function aiActUnit(u,level){let target=aiBestAttack(u,level); if(target){attack(u,target); return;} let dest=aiBestMove(u,level); if(dest&&(dest.x!==u.x||dest.y!==u.y)){u.x=dest.x;u.y=dest.y;u.moved=true; log(`${state.players[u.owner].name}'s ${u.type} advances to ${u.x},${u.y}.`); sfx('move'); if(canCapture(u)){let tt=tile(u.x,u.y); if(tt.s&&tt.owner!==u.owner){tt.owner=u.owner; log(`${state.players[u.owner].name} captures ${STRUCTS[tt.s].name}.`);}}} u.acted=true;}
function aiBestAttack(u,level){let targets=state.units.filter(e=>e.owner!==u.owner&&e.hp>0&&dist(u,e)<=UNITS[u.type].range); if(!targets.length)return null; targets.sort((a,b)=>aiAttackScore(u,b,level)-aiAttackScore(u,a,level)); let best=targets[0]; if(level.rank<=1&&rng()<.25)return targets[Math.floor(rng()*targets.length)]; return best;}
function aiAttackScore(u,e,level){let p=combatPreview(u,e), score=p.detail.damage*level.aggression; if(p.afterD<=0)score+=45; if(e.type==='Commander')score+=70; if(e.hp/e.maxHp<.4)score+=18; if(p.counter)score-=p.cd*level.caution; if(p.detail.counter)score+=25; score-=terrainDefenseAt(tile(e.x,e.y))*2; return score;}
function aiBestMove(u,level){let goals=[]; if(canCapture(u))state.map.filter(t=>t.s&&t.owner!==u.owner).forEach(t=>goals.push({x:t.x,y:t.y,score:t.owner===null?35:55})); state.units.filter(e=>e.owner!==u.owner&&e.hp>0).forEach(e=>goals.push({x:e.x,y:e.y,score:e.type==='Commander'?100:50})); if(!goals.length)return null; let goal=goals.sort((a,b)=>(Math.abs(u.x-a.x)+Math.abs(u.y-a.y)-a.score/20)-(Math.abs(u.x-b.x)+Math.abs(u.y-b.y)-b.score/20))[0]; let candidates=[]; for(let y=0;y<state.h;y++)for(let x=0;x<state.w;x++){let d=Math.abs(x-u.x)+Math.abs(y-u.y); if(d<=UNITS[u.type].mv&&canEnter(u,x,y))candidates.push({x,y});} candidates.push({x:u.x,y:u.y}); candidates.sort((a,b)=>aiMoveScore(u,b,goal,level)-aiMoveScore(u,a,goal,level)); return candidates[0];}
function aiMoveScore(u,c,goal,level){let tt=tile(c.x,c.y), score=0; score-=Math.abs(c.x-goal.x)+Math.abs(c.y-goal.y); score+=terrainDefenseAt(tt)*level.caution; if(tt.s&&tt.owner!==u.owner&&canCapture(u))score+=45; let enemies=state.units.filter(e=>e.owner!==u.owner&&e.hp>0); let danger=enemies.some(e=>Math.abs(e.x-c.x)+Math.abs(e.y-c.y)<=UNITS[e.type].range); if(danger&&u.type==='Commander')score-=80*level.caution; return score;}

function saveGame(){if(!state){alert('No game to save.');return;} let data=JSON.stringify(state,null,2); let blob=new Blob([data],{type:'application/json'}); let a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=suggestedSaveName(); a.click(); URL.revokeObjectURL(a.href);}
function loadGameFile(e){let f=e.target.files[0]; if(!f)return; let reader=new FileReader(); reader.onload=()=>{try{state=JSON.parse(reader.result); selected=null; highlights=[]; rng=seeded(state.seed||'loaded'); for(let i=0;i<state.turn*97+state.current*13;i++)rng(); state.version=state.version||VERSION; state.turnEvents=state.turnEvents||[]; log(`Game loaded from Discord save file. Current player: ${player().name}. Turn ${state.turn}.`); setThemeForCurrent(); render(); maybeRunAI(); alert(`Loaded Iron Kingdoms save.\nTurn ${state.turn}: ${player().name} acts now.\nAlive: ${state.players.filter(p=>p.alive).map(p=>p.name).join(', ')}\nObservers: ${state.players.filter(p=>p.observer).map(p=>p.name).join(', ')||'None'}`);}catch(err){alert('Could not load save: '+err.message)}}; reader.readAsText(f); e.target.value='';}
function renderLog(){$('log').innerHTML=(state?state.log:[]).map(l=>`<div class="logLine">${l}</div>`).join('')}
function showTurnToast(msg){let wrap=$('mapWrap'); if(!wrap)return; let el=document.createElement('div'); el.className='turnToast'; el.textContent=msg; wrap.appendChild(el); setTimeout(()=>el.remove(),3000)}
loadAudioSettings();
openNewGame();
